"""Simple Streamlit dashboard for the ISMS ISO Toolkit (hobby project).

Run with:
    streamlit run dashboard/app.py

Loads the committed example artifacts from examples/.
"""

import streamlit as st
import pandas as pd
from pathlib import Path
from openpyxl import load_workbook

st.set_page_config(page_title="ISMS Toolkit — Aether Labs (Hobby)", layout="wide")

ROOT = Path(__file__).resolve().parents[1]
RISK_XLSX = ROOT / "examples" / "risk-register-aether-labs.xlsx"
GAP_XLSX = ROOT / "examples" / "gap-analysis-aether-labs.xlsx"

st.title("ISMS ISO Toolkit — Hobby Explorer")
st.caption("Personal project for ISO 27001:2022 risk & compliance automation (fictional Aether Labs)")

with st.sidebar:
    st.header("About")
    st.markdown("""
    This dashboard demonstrates the artifacts generated by the toolkit.

    **Company (fictional):** Aether Labs  
    **Data source:** Committed example files in `examples/`
    """)
    if st.button("Regenerate from seeds (if scripts available)"):
        st.info("In a full implementation this would call the generators. Currently using committed examples.")

# Load data
@st.cache_data
def load_risk_data():
    wb = load_workbook(RISK_XLSX, data_only=True)
    ws = wb["Risk Register"]
    data = []
    headers = [cell.value for cell in ws[1]]
    for row in ws.iter_rows(min_row=2, values_only=True):
        if row[0]:
            data.append(dict(zip(headers, row)))
    return pd.DataFrame(data), wb

@st.cache_data
def load_gap_data():
    wb = load_workbook(GAP_XLSX, data_only=True)
    ws = wb["Annex A Controls"]
    data = []
    headers = [cell.value for cell in ws[1]]
    for row in ws.iter_rows(min_row=2, values_only=True):
        if row[0]:
            data.append(dict(zip(headers, row)))
    return pd.DataFrame(data), wb

risk_df, risk_wb = load_risk_data()
gap_df, gap_wb = load_gap_data()

tab1, tab2, tab3, tab4 = st.tabs(["Risk Overview", "Heatmap & Top Risks", "Gap Analysis", "Policies"])

with tab1:
    st.subheader("Risk Register Overview")
    st.dataframe(risk_df, use_container_width=True, height=400)
    st.metric("Total Risks", len(risk_df))

with tab2:
    st.subheader("5×5 Heatmap + Top Risks")
    # Simple display of heatmap sheet info
    st.write("See the committed Excel for the full colored heatmap. Top risks from generator:")
    st.dataframe(risk_df.nsmallest(5, columns=["Inherent Score"]) if "Inherent Score" in risk_df.columns else risk_df.head(5))

with tab3:
    st.subheader("Annex A Gap Analysis")
    st.dataframe(gap_df, use_container_width=True, height=400)
    st.write("Summary (from Excel): 93 controls considered")

with tab4:
    st.subheader("Policy Templates")
    st.markdown("""
    Policies are stored in the `policies/` directory as Markdown templates.

    - [Information Security Policy](../policies/information-security-policy.md)
    - [Acceptable Use](../policies/acceptable-use.md)
    - And others...

    Each contains explicit Annex A references.
    """)

st.markdown("---")
st.caption("Hobby project — all data is fictional and for demonstration only.")
