"""Generate Annex A gap analysis Excel (hobby toolkit)."""

from pathlib import Path
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

from ..gap.analysis import get_all_gaps, summarize_gaps

STATUS_COLORS = {
    "Implemented": "90EE90",
    "Partially Implemented": "FFFF00",
    "Not Implemented": "FFA500",
    "Not Applicable": "D3D3D3",
}


def create_gap_workbook(controls: list[dict], company: str = "Aether Labs") -> Workbook:
    wb = Workbook()

    # Document control
    ws_doc = wb.active
    ws_doc.title = "Document Control"
    ws_doc["A1"] = "ISO 27001:2022 Annex A Gap Analysis"
    ws_doc["A1"].font = Font(bold=True, size=16)
    ws_doc["A3"] = "Company (fictional):"
    ws_doc["B3"] = company
    ws_doc["A4"] = "Generated by:"
    ws_doc["B4"] = "ISMS-ISO-toolkit (hobby project)"
    ws_doc["A5"] = "Version:"
    ws_doc["B5"] = "0.1.0"
    ws_doc["A7"] = "Note: Fictional data for educational purposes only."

    # Main controls checklist
    ws = wb.create_sheet("Annex A Controls")
    headers = ["ID", "Theme", "Control Title", "Status", "Evidence / Notes", "Owner", "Priority"]
    for col, h in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col, value=h)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
        cell.alignment = Alignment(wrap_text=True)

    gaps = get_all_gaps(controls)

    for row_idx, g in enumerate(gaps, 2):
        ws.cell(row=row_idx, column=1, value=g["id"])
        ws.cell(row=row_idx, column=2, value=g["theme"])
        ws.cell(row=row_idx, column=3, value=g["title"])
        status_cell = ws.cell(row=row_idx, column=4, value=g["status"])
        color = STATUS_COLORS.get(g["status"])
        if color:
            status_cell.fill = PatternFill(start_color=color, end_color=color, fill_type="solid")
        ws.cell(row=row_idx, column=5, value=g["notes"])
        ws.cell(row=row_idx, column=6, value=g["owner"])
        ws.cell(row=row_idx, column=7, value=g["priority"])

    # Auto filter + width
    ws.auto_filter.ref = ws.dimensions
    ws.freeze_panes = "A2"
    for col_idx in range(1, 8):
        ws.column_dimensions[get_column_letter(col_idx)].width = 35 if col_idx == 5 else 22

    # Summary
    ws_sum = wb.create_sheet("Summary")
    summary = summarize_gaps(gaps)
    ws_sum["A1"] = "Gap Analysis Summary"
    ws_sum["A1"].font = Font(bold=True, size=14)
    ws_sum["A3"] = "Total controls considered:"
    ws_sum["B3"] = summary["total"]

    row = 5
    for theme, counts in summary["by_theme"].items():
        ws_sum.cell(row=row, column=1, value=theme).font = Font(bold=True)
        row += 1
        for status, cnt in counts.items():
            ws_sum.cell(row=row, column=1, value=f"  {status}")
            ws_sum.cell(row=row, column=2, value=cnt)
            row += 1
        row += 1

    # Statement of Applicability excerpt (example)
    ws_soa = wb.create_sheet("SoA Excerpt")
    ws_soa["A1"] = "Statement of Applicability (excerpt) - Fictional"
    ws_soa["A1"].font = Font(bold=True, size=14)
    ws_soa["A3"] = "Applicable controls selected based on risk assessment for Aether Labs scope."
    ws_soa["A5"] = "Control ID"
    ws_soa["B5"] = "Title"
    ws_soa["C5"] = "Justification / Implementation Note"
    for c in ws_soa[5]:
        c.font = Font(bold=True)
        c.fill = PatternFill(start_color="D9E1F2", end_color="D9E1F2", fill_type="solid")

    # Pick some "applicable" ones (high priority or implemented)
    applicable = [g for g in gaps if g["status"] in ("Implemented", "Partially Implemented")][:12]
    for i, g in enumerate(applicable, 6):
        ws_soa.cell(row=i, column=1, value=g["id"])
        ws_soa.cell(row=i, column=2, value=g["title"])
        ws_soa.cell(row=i, column=3, value=g["notes"] or "In scope per risk treatment plan.")

    for col in range(1, 4):
        ws_soa.column_dimensions[get_column_letter(col)].width = 45

    return wb


def save_workbook(wb: Workbook, path: str | Path):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)
    print(f"Saved gap analysis to {path}")
