"""Generate professional risk register Excel workbook (hobby toolkit).

Uses openpyxl for formatting, conditional colors, multiple sheets.
"""

from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill

from ..risk.calculator import calculate_inherent_risk, rating_from_score

RATING_COLORS = {
    "Critical": "FF0000",   # red
    "High": "FFA500",       # orange
    "Medium": "FFFF00",     # yellow
    "Low": "90EE90",        # light green
}


def _style_header(ws, row=1):
    header_fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF")
    for cell in ws[row]:
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)


def _auto_width(ws):
    for col in ws.columns:
        max_length = 0
        column = col[0].column_letter
        for cell in col:
            try:
                if cell.value:
                    max_length = max(max_length, len(str(cell.value)))
            except Exception:
                pass
        ws.column_dimensions[column].width = min(max_length + 2, 45)


def create_risk_workbook(risks: list[dict], company: str = "Aether Labs") -> Workbook:
    wb = Workbook()

    # 1. Document Control
    ws_doc = wb.active
    ws_doc.title = "Document Control"
    ws_doc["A1"] = "ISMS Risk Register"
    ws_doc["A1"].font = Font(bold=True, size=16)
    ws_doc["A3"] = "Company (fictional):"
    ws_doc["B3"] = company
    ws_doc["A4"] = "Generated by:"
    ws_doc["B4"] = "ISMS-ISO-toolkit (hobby project)"
    ws_doc["A5"] = "Version:"
    ws_doc["B5"] = "0.1.0"
    ws_doc["A6"] = "Classification:"
    ws_doc["B6"] = "Internal - Hobby / Educational"
    ws_doc["A8"] = "Note: All data is fictional and for demonstration purposes only."

    # 2. Risk Register
    ws_risk = wb.create_sheet("Risk Register")
    headers = [
        "ID", "Asset", "Threat", "Vulnerability", "Likelihood", "Impact",
        "Inherent Score", "Rating", "Existing Controls", "Treatment",
        "Owner", "Review Date", "Status", "Notes"
    ]
    for col, h in enumerate(headers, 1):
        ws_risk.cell(row=1, column=col, value=h)
    _style_header(ws_risk)

    for row_idx, r in enumerate(risks, 2):
        score, rating = calculate_inherent_risk(r["likelihood"], r["impact"])
        ws_risk.cell(row=row_idx, column=1, value=r.get("id"))
        ws_risk.cell(row=row_idx, column=2, value=r.get("asset"))
        ws_risk.cell(row=row_idx, column=3, value=r.get("threat"))
        ws_risk.cell(row=row_idx, column=4, value=r.get("vulnerability", ""))
        ws_risk.cell(row=row_idx, column=5, value=r["likelihood"])
        ws_risk.cell(row=row_idx, column=6, value=r["impact"])
        ws_risk.cell(row=row_idx, column=7, value=score)
        rating_cell = ws_risk.cell(row=row_idx, column=8, value=rating)
        if rating in RATING_COLORS:
            color = RATING_COLORS[rating]
            rating_cell.fill = PatternFill(
                start_color=color, end_color=color, fill_type="solid"
            )
        ws_risk.cell(row=row_idx, column=9, value=r.get("existing_controls", ""))
        ws_risk.cell(row=row_idx, column=10, value=r.get("treatment", "Mitigate"))
        ws_risk.cell(row=row_idx, column=11, value=r.get("owner", ""))
        ws_risk.cell(row=row_idx, column=12, value=r.get("review_date", ""))
        ws_risk.cell(row=row_idx, column=13, value=r.get("status", "Open"))
        ws_risk.cell(row=row_idx, column=14, value=r.get("notes", ""))

    _auto_width(ws_risk)
    ws_risk.auto_filter.ref = ws_risk.dimensions
    ws_risk.freeze_panes = "A2"

    # 3. Heatmap (simple count grid)
    ws_heat = wb.create_sheet("Heatmap")
    ws_heat["A1"] = "5x5 Risk Heatmap (Likelihood x Impact) - Count of risks"
    ws_heat["A1"].font = Font(bold=True, size=14)

    # Header row for impact 1-5
    ws_heat.cell(row=3, column=1, value="Likelihood \\ Impact")
    for i in range(1, 6):
        ws_heat.cell(row=3, column=i+1, value=i)

    # Build matrix
    matrix = [[0 for _ in range(5)] for _ in range(5)]
    for r in risks:
        lik_idx = r["likelihood"] - 1
        imp_idx = r["impact"] - 1
        matrix[lik_idx][imp_idx] += 1

    for lik_idx in range(5):
        ws_heat.cell(row=4 + lik_idx, column=1, value=lik_idx + 1)
        for imp_idx in range(5):
            cell = ws_heat.cell(row=4 + lik_idx, column=imp_idx + 2, value=matrix[lik_idx][imp_idx])
            score = (lik_idx + 1) * (imp_idx + 1)
            rating = rating_from_score(score)
            if rating in RATING_COLORS:
                color = RATING_COLORS[rating]
                cell.fill = PatternFill(start_color=color, end_color=color, fill_type="solid")

    ws_heat["A10"] = "Legend: Green=Low, Yellow=Medium, Orange=High, Red=Critical"
    ws_heat["A11"] = f"Total risks: {len(risks)}"

    # 4. Summary
    ws_sum = wb.create_sheet("Summary")
    ws_sum["A1"] = "Risk Summary"
    ws_sum["A3"] = "Total risks:"
    ws_sum["B3"] = len(risks)
    # Simple counts
    counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0}
    for r in risks:
        _, rat = calculate_inherent_risk(r["likelihood"], r["impact"])
        counts[rat] += 1
    ws_sum["A5"] = "By rating:"
    row = 6
    for rat, cnt in counts.items():
        ws_sum.cell(row=row, column=1, value=rat)
        ws_sum.cell(row=row, column=2, value=cnt)
        row += 1

    return wb


def save_workbook(wb: Workbook, path: str | Path):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)
    print(f"Saved risk register to {path}")
